USE CURSO;
GO

CREATE PROCEDURE IMC @PESO DECIMAL(10,2), @ALTURA DECIMAL(10,2)
AS
BEGIN
    DECLARE @IMC DECIMAL(10,2);

    SET @IMC = @PESO / (@ALTURA * @ALTURA);

    IF @IMC < 17
        BEGIN
            PRINT 'SEU IMC É: ' + CAST(@IMC AS VARCHAR(20)) + 'E ESTÁ COM O PESO MUITO BAIXO';
        END
    ELSE IF @IMC >= 17 AND @IMC <= 18.49
        BEGIN
            PRINT 'SEU IMC É: ' + CAST(@IMC AS VARCHAR(20)) + 'E ESTÁ COM O PESO ABAIXO DO NORMAL';
        END
    ELSE IF @IMC > 18.5 AND @IMC <= 24.99
        BEGIN
            PRINT 'SEU IMC É: ' + CAST(@IMC AS VARCHAR(20)) + 'E ESTÁ COM O PESO NORMAL';
        END
END;

EXEC IMC 70, 1.80;

