--DISABLE TRIGGER TG_AUD_SAL ON SALARIO;
--ENABLE TRIGGER TG_AUD_SAL ON SALARIO;
USE CURSO
GO

--ESSA TRIGGER SÓ FUNCIONA QUANDO É ALTERADO UM SÓ REGISTRO E DÁ ERRO SE FIZER:
--UPDATE SALARIO SET SALARIO = SALARIO * 1.20; POR EXEMPLO

CREATE TRIGGER TG_AUD_SAL ON SALARIO
AFTER UPDATE
AS 
BEGIN
    DECLARE @MATRICULA INT;
    DECLARE @SAL_ANTIGO DECIMAL(10,2),
    DECLARE SAL_NOVO DECIMAL(10,2);

    @MATRICULA = (SELECT MATRICULA FROM SALARIO INSERTED);
    @SAL_ANTIGO = (SELECT SALARIO FROM SALARIO DELETED);
    @SAL_NOVO = (SELECT SALARIO FROM SALARIO INSERTED);

    INSERT INTO AUDITORIA_SALARIO VALUES (
        @MATRICULA,
        ISNULL(@SAL_ANTIGO, 0),
        @SAL_NOVO,
        SYSTEM_USER,
        GETDATE()
    )
END;

-- TESTANDO A TRIGGER
UPDATE SALARIO SET SALARIO = 1500 WHERE MATRICULA = 1;
UPDATE SALARIO SET SALARIO = 2500 WHERE MATRICULA = 2;
UPDATE SALARIO SET SALARIO = 3500 WHERE MATRICULA = 3;
