USE CURSO;
GO

CREATE TABLE FUNC (
    MATRICULA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    DATA_NASC DATETIME NOR NULL
);

INSERT INTO FUNC VALUES (
    'Vinícius',
    'Amirat',
    'rua tal',
    'Jundiaí',
    'sp',
    '2003-21-10'
);

INSERT INTO FUNC VALUES (
    'Júlia',
    'Amirat',
    'rua tal',
    'Jundiaí',
    'sp',
    '2004-04-05'
);

INSERT INTO FUNC VALUES (
    'Juliano',
    'Amirat',
    'rua tal',
    'Jundiaí',
    'sp',
    '1999-06-10'
);

CREATE TABLE AUDITORIA_SALARIO(
    MATRICULA VARCHAR(50) NOT NULL,
    SAL_ANTES DECIMAL(10,2) NOT NULL,
    SAL_DEPOIS DECIMAL(10,2) NOT NULL,
    USUARIO VARCHAR(20) NOT NULL,
    DATA_ATUALIZACAO DATETIME NOT NULL
);

CREATE TABLE SALARIO(
    MATRICULA INT NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL
);

INSERT INTO SALARIO (1, 1000);
INSERT INTO SALARIO (2, 2000);
INSERT INTO SALARIO (3, 3000);